### ISSUE TITLE
Any plans to make this library Dart 2 compatible?

### ISSUE THREAD

**Issue by martflu** [analogic/cookie#2]

**Comment by jodinathan** [comment]
created a PR fixing it for Dart 2.

You can use my fork for now: https://github.com/jodinathan/cookie

**Comment by martflu** [comment]
Thanks. It seems that @analogic is not really maintaining this library anymore. We will probably publish our own cookie lib.

**Comment by jodinathan** [comment]
I will wait some time and will publish a new package if no answer

**Comment by martflu** [comment]
We already added [cooky](https://pub.dartlang.org/packages/cooky)
